//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kashef.Common.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kashef.Common.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A x509 certicate does not contain a private key for decryption.
        /// </summary>
        internal static string CertificateHasNoPrivateKey {
            get {
                return ResourceManager.GetString("CertificateHasNoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string Constant_START {
            get {
                return ResourceManager.GetString("Constant_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string Constant_STOP {
            get {
                return ResourceManager.GetString("Constant_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cacheItemConfig is null.
        /// </summary>
        internal static string Exception_CacheItemKeyNull {
            get {
                return ResourceManager.GetString("Exception_CacheItemKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform this operation.ChangeTracker is null or ObjectState is invalid for this operation.
        /// </summary>
        internal static string Exception_ChangeTrackerIsNullOrStateIsNOK {
            get {
                return ResourceManager.GetString("Exception_ChangeTrackerIsNullOrStateIsNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container cannot be null.
        /// </summary>
        internal static string Exception_ContainerCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_ContainerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default IocContainer setting not found.
        /// </summary>
        internal static string Exception_DefaultIOCSettings {
            get {
                return ResourceManager.GetString("Exception_DefaultIOCSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression path is null or not a valid expression function.
        /// </summary>
        internal static string Exception_ExpressionPathNotValid {
            get {
                return ResourceManager.GetString("Exception_ExpressionPathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterExpression cannot be null.
        /// </summary>
        internal static string Exception_FilterCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_FilterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include path cannot be null or empty string.
        /// </summary>
        internal static string Exception_IncludePathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception_IncludePathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex*PageCount produce overflow exception.
        /// </summary>
        internal static string Exception_InvalidElementsInPage {
            get {
                return ResourceManager.GetString("Exception_InvalidElementsInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageCount is less than zero.
        /// </summary>
        internal static string Exception_InvalidPageCount {
            get {
                return ResourceManager.GetString("Exception_InvalidPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex is less than zero.
        /// </summary>
        internal static string Exception_InvalidPageIndex {
            get {
                return ResourceManager.GetString("Exception_InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace message is null or empty string.
        /// </summary>
        internal static string Exception_InvalidTraceMessage {
            get {
                return ResourceManager.GetString("Exception_InvalidTraceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is null.
        /// </summary>
        internal static string Exception_ItemArgumentIsNull {
            get {
                return ResourceManager.GetString("Exception_ItemArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not mapped found for type {0} to type {1}.
        /// </summary>
        internal static string Exception_NotMapFoundForTypeAdapter {
            get {
                return ResourceManager.GetString("Exception_NotMapFoundForTypeAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderByExpression cannot be null.
        /// </summary>
        internal static string Exception_OrderByExpressionCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_OrderByExpressionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification cannot be null.
        /// </summary>
        internal static string Exception_SpecificationIsNull {
            get {
                return ResourceManager.GetString("Exception_SpecificationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace manager cannot be null.
        /// </summary>
        internal static string Exception_TraceManagerCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_TraceManagerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A x509 certificate and string for decryption must be provided.
        /// </summary>
        internal static string InValidDecryptionParams {
            get {
                return ResourceManager.GetString("InValidDecryptionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A x509 certificate and string for encryption must be provided.
        /// </summary>
        internal static string InValidEncryptionParams {
            get {
                return ResourceManager.GetString("InValidEncryptionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A x509 certificate and string for signing must be provided.
        /// </summary>
        internal static string InValidSigningParams {
            get {
                return ResourceManager.GetString("InValidSigningParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A x509 certificate and string for verifying must be provided.
        /// </summary>
        internal static string InValidVerifiyingParams {
            get {
                return ResourceManager.GetString("InValidVerifiyingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license object is null.
        /// </summary>
        internal static string LicenseIsNull {
            get {
                return ResourceManager.GetString("LicenseIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added object of type {0} in repository.
        /// </summary>
        internal static string Trace_AddedItemRepository {
            get {
                return ResourceManager.GetString("Trace_AddedItemRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied changes of type {0} in repository.
        /// </summary>
        internal static string Trace_AppliedChangedItemRepository {
            get {
                return ResourceManager.GetString("Trace_AppliedChangedItemRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached item in repository of type {0}.
        /// </summary>
        internal static string Trace_AttachedItemToRepository {
            get {
                return ResourceManager.GetString("Trace_AttachedItemToRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created repository for type {0}.
        /// </summary>
        internal static string Trace_ConstructRepository {
            get {
                return ResourceManager.GetString("Trace_ConstructRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted object of type {0} in repository.
        /// </summary>
        internal static string Trace_DeletedItemRepository {
            get {
                return ResourceManager.GetString("Trace_DeletedItemRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAll called in repository of type {0}.
        /// </summary>
        internal static string Trace_GetAllRepository {
            get {
                return ResourceManager.GetString("Trace_GetAllRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get items by specification in repository of type {0}.
        /// </summary>
        internal static string Trace_GetBySpec {
            get {
                return ResourceManager.GetString("Trace_GetBySpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFilteredElements called in repository of type {0} with Filter:{1}.
        /// </summary>
        internal static string Trace_GetFilteredElementsRepository {
            get {
                return ResourceManager.GetString("Trace_GetFilteredElementsRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFilteredElements called in repository of type {0} with Filter:{1} PageIndex:{2} PageCount:{3} OrderBy:{4}.
        /// </summary>
        internal static string Trace_GetFilteredPagedElementsRepository {
            get {
                return ResourceManager.GetString("Trace_GetFilteredPagedElementsRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPagedElements called in repository of type {0} with PageIndex:{1},PageCount:{2},OrderBy:{3}.
        /// </summary>
        internal static string Trace_GetPagedElementsRepository {
            get {
                return ResourceManager.GetString("Trace_GetPagedElementsRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneGate SSO Trial Version is expired..
        /// </summary>
        internal static string TrialVersionIsExpired {
            get {
                return ResourceManager.GetString("TrialVersionIsExpired", resourceCulture);
            }
        }
    }
}
